mysite/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blog_with_date, name='blog_with_date'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('likes/', include('likes.urls')),
    path('user/', include('user.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('my_notifications/', include('my_notifications.urls')),
    path('search/', views.search, name='search'),
]

# 上传的图片是到media中，不是在static中，还需设置media可被访问
# 如下设置可用于开发中使用，若部署到服务器可用服务器软件设置
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/', views.change_nickname, name='change_nickname'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('change_password/', views.change_password, name='change_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
]

mysite/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    左撇子招牌字 | 关于
{% endblock %}

{% block nav_home_active %}
    active
{% endblock %}

mysite/templates/base.html
{% load staticfiles %}
{% load notifications_tags %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'base.css' %}?_-2020042301">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery-3.4.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'notifications/notify.js' %}"></script>
    {% block header_extends %}
        
    {% endblock %}
</head>

<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">左撇子招牌字</a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="{% block nav_home_active %}
                                
                               {% endblock %}"
                    >
                        <a href="{% url 'home' %}">首页</a>
                    </li>
                    <li class="{% block nav_blog_active %}
                    
                               {% endblock %}"
                    >
                        <a href="{% url 'blog_list' %}">博客</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form class="navbar-form search-form" action="{% url 'search' %}">
                            <div class="form-group">
                                <input type="text" name="wd" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </form>
                    </li>

                    {% if not user.is_authenticated %}
                        <li>
                            <a href="{% url 'user:login' %}?from={{ request.get_full_path }}">登录</a>
                        </li>
                        <li>
                            <a href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a>
                        </li>
                    {% else %}
                        {% notifications_unread as unread_count %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                                你好，{{ user.get_nickname_or_username }}
                                <span class="badge unread-count live_notify_badge">{% if unread_count > 0 %}{{ unread_count }}{% endif %}</span>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'user:user_info' %}">个人资料</a></li>
                                <li>
                                    <a href="{% url 'my_notifications' %}">
                                        消息中心
                                        <span class="badge unread-count live_notify_badge">{% if unread_count > 0 %}{{ unread_count }}{% endif %}</span>
                                    </a>
                                </li>
                                {% if user.is_staff or user.is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                                {% endif %}
                                <li><a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

    {% block content %}

    {% endblock %}

    <!-- footer -->
    <div class="footer">
        <div class="website-info">
            <p>Powered by Django & Bootstrap </p>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="login_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <form id="login_medal_form" action="" method="POST">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">登录</h4>
                    </div>

                    <div class="modal-body">
                        {% csrf_token %}
                        {% for field in login_modal_form %}
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        {% endfor %}
                        <span id="login_medal_tip" class="text-danger"></span>
                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">登录</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>                        
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $("#login_medal_form").submit(function(event){
            event.preventDefault();
            $.ajax({
                url: '{% url "user:login_for_medal" %}',
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data){
                    if(data['status']=='SUCCESS'){
                        window.location.reload();
                    }else{
                        $('#login_medal_tip').text('用户名或密码不正确');
                    }
                }
            });
        });

        //底部栏置底
        //窗体改变大小事件
        $(window).resize(function(){
            //正文高度
            var body_height = $(document.body).outerHeight(true);
            //底部元素高度
            var bottom_height = $("#footer").outerHeight(true);
            //浏览器页面高度
            var window_height = $(window).height();
            
            //判断并调整底部元素的样式
            if($(".footer").hasClass('page-bottom')){
                //若包含有page-bottom类，就应用了position设置
                //当position为absolute时，body高度不包含这个元素
                //所以页面高度需要判断body和footer之和若小于浏览器窗口
                //则移除样式，让footer自然跟随在正文后面
                if(body_height + bottom_height >= window_height){
                    $(".footer").removeClass('page-bottom');
                }
            }else{
                //若没有page-bottom类，body高度包含footer
                //判断body高度小于浏览器时，则悬浮于底部
                if(body_height < window_height){
                    $(".footer").addClass('page-bottom');
                }
            }
        });
        //页面加载时，模拟触发一下resize事件
        $(window).trigger('resize');

        //自定义实时获取未读消息
        function my_special_notification_callback(data){
            unread_count = data['unread_count'];
            if (unread_count == 0) {
                unread_count = '';
            }
            $('.live_notify_badge').text(unread_count);
        }
    </script>
    {% register_notify_callbacks callbacks='my_special_notification_callback' %}

    {% block script_extends %}
        
    {% endblock %}
</body>
</html>

mysite/templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    左撇子招牌字 | 错误
{% endblock %}

{% block nav_home_active %}
    active
{% endblock %}

{% block content %}
    {{ message }}，<a href="{{ redirect_to }}">返回</a>
{% endblock %}

mysite/templates/form.html
{% extends 'base.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block nav_home_active %}
    active
{% endblock %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="tip" class="text-danger">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}

                                {% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary">
                                <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                            </div>
                            
                        </form>
                    </div>
                </div>            
            </div>
        </div>
    </div>    
{% endblock %}

mysite/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    左撇子招牌字 | 首页
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
    <script src="http://cdn.hcharts.cn/highcharts/highcharts-3d.js"></script>
{% endblock %}

{# 当前栏目颜色突出显示 #}
{% block nav_home_active %}
    active
{% endblock %}

{% block content %}
    <h3 class="home-content">欢迎到访小破站</h3>
    <!-- 图表容器 DOM -->
    <div id="container"></div>

    <div id="wrap">
        <div class="hot-data">
            <h3>昨日热门点击</h3>
            <ul>
                {% for hot_data in yesterday_hot_data %}
                    <li><a href="{% url 'blog_detail' hot_data.content_object.pk %}">{{ hot_data.content_object.title }}</a>（{{ hot_data.read_num }}）</li>
                {% empty %}
                    <li>昨日暂无热门博客</li>
                {% endfor %}
            </ul>
        </div>

        <div class="hot-data">
            <h3>今日热门点击</h3>
            <ul>
                {% for hot_data in today_hot_data %}
                    <li><a href="{% url 'blog_detail' hot_data.content_object.pk %}">{{ hot_data.content_object.title }}</a>（{{ hot_data.read_num }}）</li>
                {% empty %}
                    <li>今日暂无热门博客</li>
                {% endfor %}
            </ul>
        </div>

        <div class="hot-data">
            <h3>一周热门点击</h3>
            <ul>
                {% for hot_blog in seven_days_hot_blog %}
                    <li><a href="{% url 'blog_detail' hot_blog.id %}">{{ hot_blog.title }}</a>（{{ hot_blog.read_num_sum }}）</li>
                {% empty %}
                    <li>一周内暂无热门博客</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <script>
        // 图表配置
        var chart = Highcharts.chart('container',{
            chart: {
                type: 'column',
                margin: 75,
                options3d: {
                    enabled: true,
                    alpha: 10,
                    beta: 25,
                    depth: 70,
                    viewDistance: 100,      // 视图距离，它对于计算角度影响在柱图和散列图非常重要。此值不能用于3D的饼图
                    frame: {                // Frame框架，3D图包含柱的面板，我们以X ,Y，Z的坐标系来理解，X轴与 Z轴所形成
                        // 的面为bottom，Y轴与Z轴所形成的面为side，X轴与Y轴所形成的面为back，bottom、
                        // side、back的属性一样，其中size为感官理解的厚度，color为面板颜色
                        bottom: {
                            size: 10
                        },
                        side: {
                            size: 1,
                            color: 'transparent'
                        },
                        back: {
                            size: 1,
                            color: 'transparent'
                        }
                    }
                },
            },
            title: {
                text: null
            },
            subtitle: {
                text: ''
            },
            plotOptions: {
                column: {
                    depth: 25
                }
            },
            xAxis: {
                categories: {{ dates|safe }},
                tickmarkPlacement: 'on',
                title: {
                    text: null
                }
            },
            yAxis: {
                title: {
                    text: null
                },
                gridLineDashStyle: 'Dash'
            },
            series: [{
                enabled: true,
                name: '阅读量',
                data: {{ read_nums }}
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            credits: { enabled: false },
        });
    </script>
{% endblock %}

mysite/templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    左撇子招牌字 | 搜索
{% endblock %}

{% block header_extends %}

{% endblock %}

{% block nav_home_active %}
    active
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% if search_words == '' %}
                    <h3>你没有搜索任何内容。</h3>
                    <p>你可以尝试输入点什么东西，例如：Django</p>
                {% else %}
                    <h3>搜索“{{ search_words }}”，找到{{ search_blogs_count }}个结果</h3>
                    <hr>
                    {% for blog in page_of_blogs %}
                        <a href="{% url 'blog_detail' blog.pk %}">
                            <h4>{{ blog.title }}</h4>
                        </a>
                        <p>{{ blog.content | striptags | truncatechars_html:100}}</p>
                    {% empty %}
                        <p>没有找到任何东西，换个关键词试试吧</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="row" style="display: flex; justify-content: center;">
            {% if page_of_blogs.has_previous %}
                <a class="btn btn-default"
                   href="{% url 'search' %}?wd={{ search_words }}&page={{ page_of_blogs.previous_page_number }}">
                    上一页
                </a>
            {% endif %}

            {% if page_of_blogs.has_next %}
            <a class="btn btn-default"
               href="{% url 'search' %}?wd={{ search_words }}&page={{ page_of_blogs.next_page_number }}">
                下一页
            </a>
            {% endif %}
        </div>
    </div>
{% endblock %}