mysite/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blog_with_date, name='blog_with_date'),
]

mysite/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('submit_comment', views.submit_comment, name='submit_comment'),
]

mysite/likes/urls.py
from django.urls import path
from . import views

app_name = 'likes'

urlpatterns = [
    path('like_change', views.like_change, name='like_change'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('likes/', include('likes.urls')),
    path('user/', include('user.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('my_notifications/', include('my_notifications.urls')),
    path('search/', views.search, name='search'),
]

# 上传的图片是到media中，不是在static中，还需设置media可被访问
# 如下设置可用于开发中使用，若部署到服务器可用服务器软件设置
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/', views.change_nickname, name='change_nickname'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('change_password/', views.change_password, name='change_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
from django.urls import reverse

from read_statistics.models import ReadNumMixin, ReadDetail

from ckeditor_uploader.fields import RichTextUploadingField

class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name

    class Meta:
        verbose_name = '博客类型'
        verbose_name_plural = verbose_name

class Blog(models.Model, ReadNumMixin):
    title = models.CharField(max_length=50, verbose_name='标题')
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE, verbose_name='博客类型')
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    read_details = GenericRelation(ReadDetail)
    created_time = models.DateTimeField(default=timezone.now, verbose_name='创建时间')  # 创建数据时将默认写入当前的时间
    last_updated_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')  # 每次数据更新时自动写入当前时间

    def get_url(self):
        return reverse('blog_detail', kwargs={'blog_pk': self.pk})

    def get_user(self):
        return self.author

    def get_email(self):
        return self.author.email

    def __str__(self):
        return self.title
        
    class Meta:
        ordering = ['-created_time']
        verbose_name = '博客'
        verbose_name_plural = verbose_name

mysite/blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Count
from django.contrib.contenttypes.models import ContentType

from .models import Blog, BlogType
from read_statistics.utils import read_statistics_once_read


def get_blog_list_common_data(request, blogs_all_list):
    paginator = Paginator(blogs_all_list, settings.EACH_PAGE_BLOGS_NUMBER)  # 每多少篇进行一次分页
    page_num = request.GET.get('page', 1)  # 获取url的码参数，url中如果没有page这个属性，默认打开第1页
    page_of_blogs = paginator.get_page(page_num)
    current_page_num = page_of_blogs.number  # 获取当前页码
    # 获取当前页码前后各一页范围
    page_range = list(range(max(current_page_num - 1, 1), current_page_num)) + \
                list(range(current_page_num, min(current_page_num + 1, paginator.num_pages) + 1))
    # 加上省略号
    if page_range[0] - 1 >= 2:
        page_range.insert(0, '...')
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append('...')
    # 加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    # 获取博客分类的对应博客数量
    blog_types_list = BlogType.objects.annotate(blog_count=Count('blog'))
    """
    blog_types = BlogType.objects.all()
    blog_types_list= []
    for blog_type in blog_types:
        # 将 blog_count 加到 blog_type 中，是临时的
        blog_type.blog_count = Blog.objects.filter(blog_type=blog_type).count()
        # 放在列表中，临时的变为永久的
        blog_types_list.append(blog_type)
    """

    blogs = page_of_blogs.object_list

    # 获取日期归档对应的博客数量
    blog_dates = Blog.objects.dates('created_time', 'month', order="DESC")
    blog_dates_dict = {}
    for blog_date in blog_dates:
        blog_count = Blog.objects.filter(created_time__year=blog_date.year,
                                        created_time__month=blog_date.month).count()
        blog_dates_dict[blog_date] = blog_count

    context = {
        'blogs':blogs,
        'page_of_blogs':page_of_blogs, 
        'page_range':page_range,
        'blog_types':blog_types_list,
        'blog_dates':blog_dates_dict,
    }
    return context


# 博客列表
def blog_list(request):
    blogs_all_list = Blog.objects.all()
    context = get_blog_list_common_data(request, blogs_all_list)
    return render(request, 'blog/blog_list.html', context)


# 博客分类
def blogs_with_type(request, blog_type_pk):
    blog_type = BlogType.objects.get(pk=blog_type_pk)
    blogs_all_list = Blog.objects.filter(blog_type=blog_type)

    context = get_blog_list_common_data(request, blogs_all_list)
    context['blog_type'] = blog_type
    return render(request, 'blog/blogs_with_type.html', context)


# 日期归档
def blog_with_date(request, year, month):
    blogs_all_list = Blog.objects.filter(created_time__year=year, created_time__month=month)
    blogs_with_date = '%s年%s月' % (year, month)

    context = get_blog_list_common_data(request, blogs_all_list)
    context['blogs_with_date'] = blogs_with_date
    return render(request, 'blog/blogs_with_date.html', context)


# 博客详情
def blog_detail(request, blog_pk):
    blog = Blog.objects.get(pk=blog_pk)
    read_cookie = read_statistics_once_read(request, blog)
    previous_blog = Blog.objects.filter(created_time__gt=blog.created_time).last()
    next_blog = Blog.objects.filter(created_time__lt=blog.created_time).first()

    context = { 
        'blog':blog,
        'previous_blog': previous_blog,
        'next_blog': next_blog,
    }
    response = render(request, 'blog/blog_detail.html', context) # 响应
    response.set_cookie(read_cookie, 'true')  # 阅读cookie标记
    return response

mysite/blog/templates/blog/blog_detail.html
 {% extends 'base.html' %}
{% load staticfiles %}
{% load comment_tags %}
{% load likes_tags %}

{% block title %}
    {{ blog.title }}
{% endblock %}

{% block nav_blog_active %}
    active
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'blog.css' %}">
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h3>{{ blog.title }}</h3>
                <ul class="blog-info-description">
                    <li>作者：{{ blog.author }}</li>
                    <li>分类：<a href="{% url 'blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a></li>
                    <li>发表日期：{{ blog.created_time|date:"Y-m-d H:i" }}</li>
                    <li>阅读：({{ blog.get_read_num }})</li>
                    <li>评论：({% get_comment_count blog %})</li>
                </ul>
                <div class="blog-content">{{ blog.content|safe }}</div>
                <div class="like" onclick="likeChange(this, '{% get_content_type blog %}', {{ blog.pk }})">
                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status blog %}"></span>
                    <span class="liked-num">{% get_like_count blog %}</span>
                    <span>喜欢</span>
                </div>
                <div class="blog-more">
                    <p>上一篇：
                        {% if previous_blog %}
                            <a href="{% url 'blog_detail' previous_blog.pk %}">{{ previous_blog.title }}</a>
                        {% else %}
                            到顶了
                        {% endif %}
                    </p>
                    <p>下一篇：
                        {% if next_blog %}
                            <a href="{% url 'blog_detail' next_blog.pk %}">{{ next_blog.title }}</a>
                        {% else %}
                            到底了
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="comment-area">
                    <h3 class="comment-area-title">提交评论</h3>
                    {% if user.is_authenticated %}
                        <form id="comment_form" action="{% url 'comment:submit_comment' %}" method="POST" style="overflow: hidden;">
                            <label>{{ user.get_nickname_or_username }}，欢迎评论~</label>
                            <div id="reply_content_container" style="display:none;">
                                <p id="reply_title">回复：</p>
                                <div id="reply_content"></div>
                            </div>
                            {% csrf_token %}
                            {% get_comment_form blog as comment_form %}
                            {% for field in comment_form %}
                                {{ field }}
                            {%  endfor %}
                            <span id="comment_error" class="text-danger pull-left"></span>
                            <input type="submit" value="评论" class="btn btn-primary pull-right">
                        </form>
                    {% else %}
                        您尚未登录，登录后方可评论~
                        <a class="btn btn-primary" href="{% url 'user:login' %}?from={{ request.get_full_path }}">登录</a>
                        <span> or </span>
                        <a class="btn btn-danger" href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a>
                    {% endif %}
                </div>
                <div class="comment-area">
                    <h3 class="comment-area-title">评论列表</h3>
                    <div id="comment_list">
                        {% get_comment_list blog as comments %}
                        {% for comment in comments %}
                            <div id="root_{{ comment.pk }}" class="comment">
                                <span>{{ comment.user.get_nickname_or_username }}</span>
                                <span>({{ comment.comment_time|date:"Y-m-d H:i:s" }})：</span>
                                <div id="comment_{{ comment.pk }}">
                                    {{ comment.text|safe }}
                                </div>

                                <div class="like" onclick="likeChange(this, '{% get_content_type comment %}', {{ comment.pk }})">
                                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status comment %}"></span>
                                    <span class="liked-num">{% get_like_count comment %}</span>
                                </div>

                                <a href="javascript:reply({{ comment.pk }});">回复</a>
                                
                                {% for reply in comment.root_comment.all %}
                                    <div class="reply">
                                        <span>{{ reply.user.get_nickname_or_username }}</span>
                                        <span>({{ reply.comment_time|date:"Y-m-d H:i:s" }})</span>
                                        <span>回复</span>
                                        <span>{{ reply.reply_to.get_nickname_or_username }}：</span>
                                        <div id="comment_{{ reply.pk }}">
                                            {{ reply.text|safe }}
                                        </div>
                                        <div class="like" onclick="likeChange(this, '{% get_content_type reply %}', {{ reply.pk }})">
                                            <span class="glyphicon glyphicon-thumbs-up {% get_like_status reply %}"></span>
                                            <span class="liked-num">{% get_like_count reply %}</span>
                                        </div>
                                        <a href="javascript:reply({{ reply.pk }});">回复</a>
                                    </div>   
                                {% endfor %}
                            </div>
                        {% empty %}
                            <span id="no_comment">暂无评论</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        String.prototype.format = function(){
            var str = this;
            for (var i = 0; i < arguments.length; i++) {
                var str = str.replace(new RegExp('\\{' + i + '\\}', 'g'), arguments[i])
            };
            return str;
        }
        function reply(reply_comment_id){
            // 设置值
            $('#reply_comment_id').val(reply_comment_id);
            var html = $("#comment_" + reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();
            $('html').animate({scrollTop: $('#comment_form').offset().top - 60}, 300, function(){
                CKEDITOR.instances['id_text'].focus();
            });
        }
        function numFormat(num){
            return ('00' + num).substr(-2);
        }
        function timeFormat(timestamp){
            var datetime = new Date(timestamp * 1000);
            var year = datetime.getFullYear();
            var month = numFormat(datetime.getMonth() + 1);
            var day = numFormat(datetime.getDate());
            var hour = numFormat(datetime.getHours());
            var minute = numFormat(datetime.getMinutes());
            var second = numFormat(datetime.getSeconds());
            return year + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second;
        }
        $("#comment_form").submit(function(){
            // 判断是否为空
            $("#comment_error").text('');
            if(CKEDITOR.instances["id_text"].document.getBody().getText().trim()==''){
                $("#comment_error").text('评论内容不能为空');
                return false;
            }
            // 更新数据到textarea
            CKEDITOR.instances['id_text'].updateElement();
            // 异步提交
            $.ajax({
                url: "{% url 'comment:submit_comment' %}",
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data){
                    console.log(data);
                    if(data['status']=="SUCCESS"){
                        if($('#reply_comment_id').val()=='0'){
                            // 插入评论
                            var comment_html = '<div id="root_{0}" class="comment">' +
                                '<span>{1}</span>' +
                                '<span>({2})：</span>' +
                                '<div id="comment_{0}">{3}</div>' +
                                '<div class="like" onclick="likeChange(this, \'{4}\', {0})">' +
                                    '<span class="glyphicon glyphicon-thumbs-up"></span> ' +
                                    '<span class="liked-num">0</span>' +
                                '</div>' +
                                '<a href="javascript:reply({0});">回复</a>' +
                                '</div>';
                            comment_html = comment_html.format(data['pk'], data['username'], timeFormat(data['comment_time']), data['text'], data['content_type']);
                            $("#comment_list").prepend(comment_html);
                        }else{ 
                            // 插入回复
                            var reply_html = '<div class="reply">' +
                                        '<span>{1}</span>' +
                                        '<span>({2})</span>' +
                                        '<span>回复</span>' +
                                        '<span>{3}：</span>' +
                                        '<div id="comment_{0}">{4}</div>' +
                                        '<div class="like" onclick="likeChange(this, \'{5}\', {0})">' +
                                            '<span class="glyphicon glyphicon-thumbs-up\"></span> ' +
                                            '<span class="liked-num">0</span>' +
                                        '</div>' +
                                        '<a href="javascript:reply({0});">回复</a>' +
                                    '</div>';
                            reply_html = reply_html.format(data['pk'], data['username'], timeFormat(data['comment_time']), data['reply_to'], data['text'], data['content_type']);
                            $("#root_" + data['root_pk']).append(reply_html);
                        }
                        
                        // 清空编辑框的内容
                        CKEDITOR.instances['id_text'].setData('');
                        $('#reply_content_container').hide();
                        $('#reply_comment_id').val('0');
                        $('#no_comment').remove();
                        $("#comment_error").text('评论成功');
                    }else{
                        // 显示错误信息
                        $("#comment_error").text(data['message']);
                    }                    
                },
                error: function(xhr){
                    console.log(xhr);
                }
            });
            return false;
        });
        function likeChange(obj, content_type, object_id){
            var is_like = obj.getElementsByClassName('active').length == 0
            $.ajax({
                url: "{% url 'likes:like_change' %}",
                type: 'GET',
                data: {
                    content_type: content_type,
                    object_id: object_id,
                    is_like: is_like
                },
                cache: false,
                success: function(data){
                    console.log(data)
                    if(data['status']=='SUCCESS'){
                        // 更新点赞状态
                        var element = $(obj.getElementsByClassName('glyphicon'));
                        if(is_like){
                            element.addClass('active');
                        }else{
                            element.removeClass('active');
                        }
                        // 更新点赞数量
                        var liked_num = $(obj.getElementsByClassName('liked-num'));
                        liked_num.text(data['liked_num']);
                    }else{
                        if(data['code']==400){
                            $('#login_modal').modal('show');
                        }else{
                            alert(data['message']);
                        }
                    }
                },
                error: function(xhr){
                    console.log(xhr)
                }
            });
        }
        if (window.location.hash) {
            $('html').animate({
                scrollTop: $(window.location.hash).offset().top - 60
            }, 500);
        }
    </script>
{% endblock %}

mysite/blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load comment_tags %}
{% load likes_tags %}

{% block title %}
    左撇子招牌字_一个基于Django的网站
{% endblock %}

{# 当前栏目颜色突出显示 #}
{% block nav_blog_active %}
    active
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'blog.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {% block blog_list_title %}
                        博客列表（共{{ page_of_blogs.paginator.count }}篇博客）
                    {% endblock %}
                </div>
                <div class="panel-body">
                    {% for blog in blogs %}
                        <div class="blog">
                            <h3><a href="{% url 'blog_detail' blog.pk %}">{{ blog.title }}</a></h3>
                            <p class="blog-info">
                                <span class="glyphicon glyphicon-tag"></span>&nbsp;&nbsp;<a href="{% url 'blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <span class="glyphicon glyphicon-time"></span>&nbsp;&nbsp;{{ blog.created_time|date:"Y-m-d" }}&nbsp;&nbsp;
                                阅读({{ blog.get_read_num }})&nbsp;&nbsp;
                                评论({% get_comment_count blog %})&nbsp;&nbsp;
                                点赞({% get_like_count blog %})
                            </p>
                            <p>{{ blog.content|safe|striptags|truncatechars:120 }}</p>
                        </div>
                    {% empty %}
                        <div class="blog">
                            <h3>-- 暂无博客，敬请期待 --</h3>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="paginator">
              <ul class="pagination">
                {# 上一页 #}
                <li>
                    {% if page_of_blogs.has_previous %}
                        <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&laquo;</span>
                    {% endif %}
                </li>

                {# 全部页码 #}
                {% for page_num in page_range %}
                    {# 当前页码高亮显示 #}
                    {% if page_num == page_of_blogs.number %}
                        <li class="active"><span>{{ page_num }}</span></li>
                    {% else %}
                        {% if page_num == '...' %}
                            <li><span>{{ page_num }}</span></li>
                        {% else %}
                            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {# 下一页 #}
                <li>
                    {% if page_of_blogs.has_next %}
                        <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                          <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&raquo;</span>
                    {% endif %}
                  
                </li>
              </ul>
              <p>
                共{{ page_of_blogs.paginator.count }}篇博客，当前第{{ page_of_blogs.number }}页，
                共{{ page_of_blogs.paginator.num_pages }}页
              </p>
            </div>
        </div>

        <div class="hidden-xs col-sm-4 col-md-3 col-lg-2">
            <div class="panel panel-default">
                <div class="panel-heading">博客分类</div>
                <div class="panel-body">
                    <ul class="blog-types">
                        {% for blog_type in blog_types %}
                            <li>
                                <a href="{% url 'blogs_with_type' blog_type.pk %}">
                                    {{ blog_type.type_name }}（{{ blog_type.blog_count }}）
                                </a>
                            </li>
                        {% empty %}
                            <li>暂无分类</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">日期归档</div>
                <div class="panel-body">
                    <ul>
                        {% for blog_date, blog_count in blog_dates.items %}
                            <li>
                                <a href="{% url 'blog_with_date' blog_date.year blog_date.month %}">{{ blog_date|date:"Y年m月" }}（{{ blog_count }}）</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/blog/templates/blog/blogs_with_date.html
{% extends 'blog/blog_list.html' %}
{% load staticfiles %}

{% block title %}
    {{ blog_type.type_name }}
{% endblock %}

{% block blog_list_title %}
    日期归档：{{ blogs_with_date }}
{% endblock %}

mysite/blog/templates/blog/blogs_with_type.html
{% extends 'blog/blog_list.html' %}
{% load staticfiles %}

{% block title %}
    {{ blog_type.type_name }}
{% endblock %}

{% block blog_list_title %}
    分类：{{ blog_type.type_name }}
{% endblock %}